@startuml
title C4 Диаграмма контекста MVP по депозитам
top to bottom direction
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
skinparam linetype ortho

Person_Ext(user, "Клиент", "Пользователь интернет-банка и сайта")

System(ib, "Интернет-банк", "Управление своими депозитами")
System(abs, "АБС", "Вся магия")

Rel(user, ib, "REST", "Просмотр условий по депозитами")
Rel(user, ib, "REST", "Открытие нового депозита")
Rel(ib, abs, "Kafka topic", "Зявка на открытие нового депозита")
Rel(ib, abs, "Kafka topic", "Запрос имеющихся депозитов")

@enduml
